networks:
  niddle-network:
    name: niddle-network
    driver: bridge

services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: niddle-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: niddle
      POSTGRES_PASSWORD: niddle
      POSTGRES_DB: niddle_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U niddle -d niddle_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - niddle-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: api-dev
    image: niddle-api:dev
    container_name: niddle-api
    restart: unless-stopped
    ports:
      - '3001:3001'
    env_file:
      -  .env.docker
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - niddle-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: web-dev
    image: niddle-web:dev
    container_name: niddle-web
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      VITE_API_URL: http://api:3001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
    depends_on:
      - api
    networks:
      - niddle-network

volumes:
  pgdata:

